# Generated by Django 5.0.3 on 2024-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_category_options_product_is_sale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
